### ISSUE TITLE
Turnos Programacion

### ISSUE THREAD

**Issue by PizzaMozzarella** [ChilkGames/RPG-Luces#26]
juan va a hacer un sist por turnos para probar como encararlo. Esto no es una version definitiva, es solo una prueba.

Tambien dijo que podia probar como funcionarian cosas como un Haste o un Slow, quedamos en que eso es opcional si tiene ganas de hacerlo 

- [x] Haste

- [x] Slow

**Comment by juanpablomaggi** [comment]
El sistema de ataque por turnos esta hecho. faltan pulir detalles que estan listados en el issue mas nuevo
